apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::273354630431:user/Leela:role/eksctl-expense1-nodegroup-expense1-NodeInstanceRole-gZFMeRrcrqKl
      username: system:node:{{EC2PrivateDNSName}}
  mapUsers: |
    - groups:
      - default-trainee
      userarn: arn:aws:iam::273354630431:user/Leela
      username: Leela
kind: ConfigMap
metadata:
  creationTimestamp: "2025-03-23T01:50:54Z"
  name: aws-auth
  namespace: kube-system
  uid: 23975d5a-f8d9-4317-ba49-1e0c053b78b9
